- id: flake8-file
  name: flake8 per file
  description: This hook runs flake8 one file at a time.
  entry: flake8-file
  language: python
  types: [python]
  require_serial: True

- id: isort-file
  name: isort per file
  description: This hook runs isort one file at a time.
  entry: isort-file
  language: python
  types: [python]
  require_serial: True
